// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cdyuoadaqpbfxzfxkmbc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNkeXVvYWRhcXBiZnh6ZnhrbWJjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NTY2OTAsImV4cCI6MjA2NTAzMjY5MH0.Iezsuw9dfdk3ObsrZYa_HKQpovYYkRKnFAmYnUI4F7E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);